# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/toby/CLionProjects/TTypeRestructured

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/toby/CLionProjects/TTypeRestructured

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/toby/CLionProjects/TTypeRestructured/CMakeFiles /home/toby/CLionProjects/TTypeRestructured//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/toby/CLionProjects/TTypeRestructured/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TTypeRestructured

# Build rule for target.
TTypeRestructured: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TTypeRestructured
.PHONY : TTypeRestructured

# fast build rule for target.
TTypeRestructured/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TTypeRestructured.dir/build.make CMakeFiles/TTypeRestructured.dir/build
.PHONY : TTypeRestructured/fast

Calculate.o: Calculate.cpp.o
.PHONY : Calculate.o

# target to build an object file
Calculate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TTypeRestructured.dir/build.make CMakeFiles/TTypeRestructured.dir/Calculate.cpp.o
.PHONY : Calculate.cpp.o

Calculate.i: Calculate.cpp.i
.PHONY : Calculate.i

# target to preprocess a source file
Calculate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TTypeRestructured.dir/build.make CMakeFiles/TTypeRestructured.dir/Calculate.cpp.i
.PHONY : Calculate.cpp.i

Calculate.s: Calculate.cpp.s
.PHONY : Calculate.s

# target to generate assembly for a file
Calculate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TTypeRestructured.dir/build.make CMakeFiles/TTypeRestructured.dir/Calculate.cpp.s
.PHONY : Calculate.cpp.s

Printer.o: Printer.cpp.o
.PHONY : Printer.o

# target to build an object file
Printer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TTypeRestructured.dir/build.make CMakeFiles/TTypeRestructured.dir/Printer.cpp.o
.PHONY : Printer.cpp.o

Printer.i: Printer.cpp.i
.PHONY : Printer.i

# target to preprocess a source file
Printer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TTypeRestructured.dir/build.make CMakeFiles/TTypeRestructured.dir/Printer.cpp.i
.PHONY : Printer.cpp.i

Printer.s: Printer.cpp.s
.PHONY : Printer.s

# target to generate assembly for a file
Printer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TTypeRestructured.dir/build.make CMakeFiles/TTypeRestructured.dir/Printer.cpp.s
.PHONY : Printer.cpp.s

TType.o: TType.cpp.o
.PHONY : TType.o

# target to build an object file
TType.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TTypeRestructured.dir/build.make CMakeFiles/TTypeRestructured.dir/TType.cpp.o
.PHONY : TType.cpp.o

TType.i: TType.cpp.i
.PHONY : TType.i

# target to preprocess a source file
TType.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TTypeRestructured.dir/build.make CMakeFiles/TTypeRestructured.dir/TType.cpp.i
.PHONY : TType.cpp.i

TType.s: TType.cpp.s
.PHONY : TType.s

# target to generate assembly for a file
TType.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TTypeRestructured.dir/build.make CMakeFiles/TTypeRestructured.dir/TType.cpp.s
.PHONY : TType.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TTypeRestructured.dir/build.make CMakeFiles/TTypeRestructured.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TTypeRestructured.dir/build.make CMakeFiles/TTypeRestructured.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TTypeRestructured.dir/build.make CMakeFiles/TTypeRestructured.dir/main.cpp.s
.PHONY : main.cpp.s

nCursesConfig.o: nCursesConfig.cpp.o
.PHONY : nCursesConfig.o

# target to build an object file
nCursesConfig.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TTypeRestructured.dir/build.make CMakeFiles/TTypeRestructured.dir/nCursesConfig.cpp.o
.PHONY : nCursesConfig.cpp.o

nCursesConfig.i: nCursesConfig.cpp.i
.PHONY : nCursesConfig.i

# target to preprocess a source file
nCursesConfig.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TTypeRestructured.dir/build.make CMakeFiles/TTypeRestructured.dir/nCursesConfig.cpp.i
.PHONY : nCursesConfig.cpp.i

nCursesConfig.s: nCursesConfig.cpp.s
.PHONY : nCursesConfig.s

# target to generate assembly for a file
nCursesConfig.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TTypeRestructured.dir/build.make CMakeFiles/TTypeRestructured.dir/nCursesConfig.cpp.s
.PHONY : nCursesConfig.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TTypeRestructured"
	@echo "... Calculate.o"
	@echo "... Calculate.i"
	@echo "... Calculate.s"
	@echo "... Printer.o"
	@echo "... Printer.i"
	@echo "... Printer.s"
	@echo "... TType.o"
	@echo "... TType.i"
	@echo "... TType.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... nCursesConfig.o"
	@echo "... nCursesConfig.i"
	@echo "... nCursesConfig.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

